// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: api/engine/v1/engine.proto

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChessEngineService_GetBestMove_FullMethodName             = "/tomsoir.engine.v1.ChessEngineService/GetBestMove"
	ChessEngineService_EnqueueGameAnalysis_FullMethodName     = "/tomsoir.engine.v1.ChessEngineService/EnqueueGameAnalysis"
	ChessEngineService_EnqueuePositionAnalysis_FullMethodName = "/tomsoir.engine.v1.ChessEngineService/EnqueuePositionAnalysis"
	ChessEngineService_GetAnalysis_FullMethodName             = "/tomsoir.engine.v1.ChessEngineService/GetAnalysis"
)

// ChessEngineServiceClient is the client API for ChessEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChessEngineServiceClient interface {
	GetBestMove(ctx context.Context, in *GetBestMoveRequest, opts ...grpc.CallOption) (*GetBestMoveResponse, error)
	EnqueueGameAnalysis(ctx context.Context, in *EnqueueGameAnalysisRequest, opts ...grpc.CallOption) (*EnqueueGameAnalysisResponse, error)
	EnqueuePositionAnalysis(ctx context.Context, in *EnqueuePositionAnalysisRequest, opts ...grpc.CallOption) (*EnqueuePositionAnalysisResponse, error)
	GetAnalysis(ctx context.Context, in *GetAnalysisRequest, opts ...grpc.CallOption) (*GetAnalysisResponse, error)
}

type chessEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChessEngineServiceClient(cc grpc.ClientConnInterface) ChessEngineServiceClient {
	return &chessEngineServiceClient{cc}
}

func (c *chessEngineServiceClient) GetBestMove(ctx context.Context, in *GetBestMoveRequest, opts ...grpc.CallOption) (*GetBestMoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBestMoveResponse)
	err := c.cc.Invoke(ctx, ChessEngineService_GetBestMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessEngineServiceClient) EnqueueGameAnalysis(ctx context.Context, in *EnqueueGameAnalysisRequest, opts ...grpc.CallOption) (*EnqueueGameAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueGameAnalysisResponse)
	err := c.cc.Invoke(ctx, ChessEngineService_EnqueueGameAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessEngineServiceClient) EnqueuePositionAnalysis(ctx context.Context, in *EnqueuePositionAnalysisRequest, opts ...grpc.CallOption) (*EnqueuePositionAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueuePositionAnalysisResponse)
	err := c.cc.Invoke(ctx, ChessEngineService_EnqueuePositionAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chessEngineServiceClient) GetAnalysis(ctx context.Context, in *GetAnalysisRequest, opts ...grpc.CallOption) (*GetAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisResponse)
	err := c.cc.Invoke(ctx, ChessEngineService_GetAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChessEngineServiceServer is the server API for ChessEngineService service.
// All implementations must embed UnimplementedChessEngineServiceServer
// for forward compatibility.
type ChessEngineServiceServer interface {
	GetBestMove(context.Context, *GetBestMoveRequest) (*GetBestMoveResponse, error)
	EnqueueGameAnalysis(context.Context, *EnqueueGameAnalysisRequest) (*EnqueueGameAnalysisResponse, error)
	EnqueuePositionAnalysis(context.Context, *EnqueuePositionAnalysisRequest) (*EnqueuePositionAnalysisResponse, error)
	GetAnalysis(context.Context, *GetAnalysisRequest) (*GetAnalysisResponse, error)
	mustEmbedUnimplementedChessEngineServiceServer()
}

// UnimplementedChessEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChessEngineServiceServer struct{}

func (UnimplementedChessEngineServiceServer) GetBestMove(context.Context, *GetBestMoveRequest) (*GetBestMoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBestMove not implemented")
}
func (UnimplementedChessEngineServiceServer) EnqueueGameAnalysis(context.Context, *EnqueueGameAnalysisRequest) (*EnqueueGameAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueGameAnalysis not implemented")
}
func (UnimplementedChessEngineServiceServer) EnqueuePositionAnalysis(context.Context, *EnqueuePositionAnalysisRequest) (*EnqueuePositionAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueuePositionAnalysis not implemented")
}
func (UnimplementedChessEngineServiceServer) GetAnalysis(context.Context, *GetAnalysisRequest) (*GetAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnalysis not implemented")
}
func (UnimplementedChessEngineServiceServer) mustEmbedUnimplementedChessEngineServiceServer() {}
func (UnimplementedChessEngineServiceServer) testEmbeddedByValue()                            {}

// UnsafeChessEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChessEngineServiceServer will
// result in compilation errors.
type UnsafeChessEngineServiceServer interface {
	mustEmbedUnimplementedChessEngineServiceServer()
}

func RegisterChessEngineServiceServer(s grpc.ServiceRegistrar, srv ChessEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedChessEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChessEngineService_ServiceDesc, srv)
}

func _ChessEngineService_GetBestMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessEngineServiceServer).GetBestMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessEngineService_GetBestMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessEngineServiceServer).GetBestMove(ctx, req.(*GetBestMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessEngineService_EnqueueGameAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueGameAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessEngineServiceServer).EnqueueGameAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessEngineService_EnqueueGameAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessEngineServiceServer).EnqueueGameAnalysis(ctx, req.(*EnqueueGameAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessEngineService_EnqueuePositionAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueuePositionAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessEngineServiceServer).EnqueuePositionAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessEngineService_EnqueuePositionAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessEngineServiceServer).EnqueuePositionAnalysis(ctx, req.(*EnqueuePositionAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChessEngineService_GetAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChessEngineServiceServer).GetAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChessEngineService_GetAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChessEngineServiceServer).GetAnalysis(ctx, req.(*GetAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChessEngineService_ServiceDesc is the grpc.ServiceDesc for ChessEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChessEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tomsoir.engine.v1.ChessEngineService",
	HandlerType: (*ChessEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBestMove",
			Handler:    _ChessEngineService_GetBestMove_Handler,
		},
		{
			MethodName: "EnqueueGameAnalysis",
			Handler:    _ChessEngineService_EnqueueGameAnalysis_Handler,
		},
		{
			MethodName: "EnqueuePositionAnalysis",
			Handler:    _ChessEngineService_EnqueuePositionAnalysis_Handler,
		},
		{
			MethodName: "GetAnalysis",
			Handler:    _ChessEngineService_GetAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/engine/v1/engine.proto",
}
